import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import Narvbar from "@/components/Narvbar";
import { Bounce, ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";

const open_Sans = Open_Sans({
  variable: "--font-Open_Sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${open_Sans.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Narvbar></Narvbar>
        {children}
        <Footer></Footer>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
